spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://codingshuttle.com
<<<<<<< HEAD
            - name: LoggingOrdersFilter
=======
>>>>>>> 31aca04f11a329730d157821474fcd10dea59af7
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Rohit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
